# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/653327621584/locations/global/workloadIdentityPools/gihubactions/providers/gihub-prv'
          service_account: 'github-actions@vivid-motif-399214.iam.gserviceaccount.com'

      - name: 'Access secret'
        run: |-
          curl https://secretmanager.googleapis.com/v1/projects/vivid-motif-399214/secrets/my-secret/versions/1:access \
           --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: cluster1
          location: us-central1-a

      - id: get-pods
        run: kubectl get pods
